### ISSUE TITLE
Dashboard personalisieren

### ISSUE THREAD

**Issue by skyprime17** [Umweltrechner-HSRM/frontend#5]

**Comment by kinaIen** [comment]
Es ist geplant, dem User eine individualisierbare Startseite zur Verfügung zu stellen. Die gespeicherten Ansichten (Balkendiagramme,etc.) sollen nach Möglichkeit bei jeder Neuanmeldung wieder zur Verfügung stehen und nicht erneut eingegeben/angefordert werden müssen.

**Comment by skyprime17** [comment]
Kann geschlossen werden, Dashboards können von Admins angepasst werden, Nutzerspezifische Dashboards sind nicht geplant.
