### ISSUE TITLE
Formel-Editor

### ISSUE THREAD

**Issue by skyprime17** [Umweltrechner-HSRM/frontend#6]
Es muss möglich sein, im Frontend bei der Formeleingabe auf die bestehenden Variabelnamen zugreifen zu können (vollständige Liste mit allen Infos (Variabelnamen, Einheit, Kommentar, etc.). Die Variabelnamen müssen wiederum bei der Formelverarbeitung erkannt und richtig interpretiert werden. Neu eingegebene Variabeln müssen abgespeichert/der bestehenden Liste hinzugefügt werden.

**Comment by kinaIen** [comment]
abc
